Removed Hardcoded Admin Username & Password
ratishjain12/aiclubwebsite pull request #7
Opened 2023-10-29 10:04 UTC by Jay24004

this PR removed the hardcoded admin user and password and add use of environment variables for admin username and password

2023-11-05 04:29 UTC, Jay24004 commented
@ratishjain12

2023-11-05 04:34 UTC, ratishjain12 commented
I have requested some changes finish those and I'll merge it :)

2023-11-05 05:05 UTC, Jay24004 commented
> I have requested some changes finish those and I'll merge it :)

where do you request those?

2023-11-05 17:26 UTC, ratishjain12 commented
> > I have requested some changes finish those and I'll merge it :)
> 
> where do you request those?

you can check those in pending review changes or go changed files tab

2023-11-06 12:47 UTC, Jay24004 commented
> > > I have requested some changes finish those and I'll merge it :)
> > 
> > 
> > where do you request those?
> 
> you can check those in pending review changes or go changed files tab

i don't think there are any changes requested can you check ?

2023-11-06 15:32 UTC, ratishjain12 commented
![image](https://github.com/ratishjain12/aiclubwebsite/assets/43003421/a652a97d-d6ce-4f75-9331-587d5848abe4)

2023-11-06 15:32 UTC, ratishjain12 requested changes
Remove import use from this file as I dont see the use of it :)

Can you make it in client side only but just converting it to NEXT_PUBLIC convention

Also no need to use dotenv

@Jay24004

2023-11-06 15:32 UTC, ratishjain12 commented on src/pages/admin/index.tsx
> +import { useState, useEffect, use } from "react";
Remove import use from this file as I dont see the use of it :)

Can you make it in client side only but just converting it to NEXT_PUBLIC convention 

Also no need to use dotenv

@Jay24004

2023-11-06 15:44 UTC, Jay24004 commented on src/pages/admin/index.tsx
> +import { useState, useEffect, use } from "react";
I have removed the import `use` and dotenv
also, the Admin username/password should be server-side only as they are sensitive information

2023-11-08 16:04 UTC, ratishjain12 approved these changes

2023-11-08 16:04 UTC, merged